name: LockedChestsPlugin
version: 1.0
api-version: 1.20.6
main: jonyboylovespie.lockedchestplugin.LockedChestsPlugin
commands:
  trust:
    description: Trust a player with a locked chest.
    usage: /trust <player>
  lockchest:
    description: Lock or unlock a chest.
    usage: /lockchest <add|remove>
  command:
