name: LockedChestsPlugin
version: '1.4'
main: jonyboylovespie.lockedchestplugin.lockedChestsPlugin.LockedChestsPlugin
api-version: '1.21'
commands:
  trust:
    description: Trust a player with a locked chest.
    usage: /trust <player>
  lockchest:
    description: Lock or unlock a chest.
    usage: /lockchest <add|remove>
  lockinspect:
    description: Inspect owner.
    usage: /lockinspect
permissions:
  lockedchests.admin.bypass:
    description: Allows removing locks from containers without owning them.
    default: op
